apiVersion: v1
kind: Service
metadata:
  name: {{ include "dis.fullname" . }}
  labels:
    {{- include "dis.labels" . | nindent 4 }}
spec:
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: attest-https
  selector:
    {{- include "dis.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}