apiVersion: v1
kind: Service
metadata:
  name: {{ include "dis.fullname" . }}-attest
  labels:
    {{- include "dis.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: attest-http
  selector:
    {{- include "dis.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}