apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dis.fullname" . }}
  labels:
    {{- include "dis.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dis.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/env: {{ include (print $.Template.BasePath "/configenv.yaml" ) . | sha256sum }}
        checksum/stream: {{ include (print $.Template.BasePath "/configmap.yaml" ) . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dis.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dis.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          {{  range .Values.image.command -}}
            - {{ . }}
          {{ end }}
          args:
          {{  range .Values.image.args -}}
            - {{ . }}
          {{ end }}
          envFrom:
          - configMapRef:
              name: {{ include "dis.fullname" . }}-config
          env:
          - name: CONTAINER_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: CONTAINER_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
                env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          ports:
{{ toYaml .Values.ports | indent 12 }}
          livenessProbe:
{{ toYaml .Values.livenessProbe | indent 12 }}
          readinessProbe:
{{ toYaml .Values.readinessProbe | indent 12 }}
          resources:
{{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- $files := .Files.Glob ("files/streams/*") }}
            {{- range $path, $_ := $files }}
            - name: {{ $path | base | replace "." "-" }}
              mountPath: /streams/{{ $path | base }}
              subPath: {{ $path | base }}
            {{- end }}
            - name: config
              mountPath: /config/config.yaml
              subPath: config.yaml
            - name: resources
              mountPath: /config/resources.yaml
              subPath: resources.yaml
            - name: external-http-server-tls
              mountPath: /etc/ssl/certs/dis
              readOnly: true

      volumes:
        {{- range $path, $_ := $files }}
        - name: {{ $path | base | replace "." "-" }}
          configMap:
            name: {{ include "dis.fullname" $ }}-stream-config
            items:
              - key: {{ $path | base }}
                path: {{ $path | base }}
        {{- end }}
        - name: config
          configMap:
            name: {{ include "dis.fullname" . }}-stream-config
            items:
              - key: config.yaml
                path: config.yaml
        - name: resources
          configMap:
            name: {{ include "dis.fullname" . }}-stream-config
            items:
              - key: resources.yaml
                path: resources.yaml
        - name: external-http-server-tls
          projected:
            sources:
              - secret:
                  name: {{ include "dis.fullname" . }}-tls
                  items:
                    - key: tls.crt
                      path: tls.crt
                    - key: tls.key
                      path: tls.key
              - configMap:
                  name: {{ .Values.certificate.caConfigMap }}
                  items:
                    - key: root_ca.crt
                      path: root_ca.crt
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
