apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "DIS.fullname" . }}
  labels:
    {{- include "DIS.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "DIS.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/env: {{ include (print $.Template.BasePath "/configenv.yaml" ) . | sha256sum }}
        checksum/stream: {{ include (print $.Template.BasePath "/configmap.yaml" ) . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "DIS.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "DIS.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          {{  range .Values.image.command -}}
            - {{ . }}
          {{ end }}
          args:
          {{  range .Values.image.args -}}
            - {{ . }}
          {{ end }}
          envFrom:
          - configMapRef:
              name: {{ include "DIS.fullname" . }}-config
          - secretRef:
              name: {{ include "DIS.fullname" . }}-secret
          env:
          - name: CONTAINER_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: CONTAINER_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
                env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          ports:
{{ toYaml .Values.ports | indent 12 }}
          livenessProbe:
{{ toYaml .Values.livenessProbe | indent 12 }}
          readinessProbe:
{{ toYaml .Values.readinessProbe | indent 12 }}
          resources:
{{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: status
              mountPath: /streams/devicestatus.yaml
              subPath: devicestatus.yaml
            - name: status-ch
              mountPath: /streams/devicestatus-clickhouse.yaml
              subPath: devicestatus-clickhouse.yaml
            - name: dbc
              mountPath: /streams/dbcdecoding.yaml
              subPath: dbcdecoding.yaml                    
            - name: config
              mountPath: /config
            - name: logs
              mountPath: /streams/devicelogs.yaml
              subPath: devicelogs.yaml
      volumes:
        - name: status
          configMap:
            name: {{ include "DIS.fullname" . }}-stream-config
            items:
              - key: devicestatus.yaml
                path: devicestatus.yaml
        - name: logs
          configMap:
            name: {{ include "DIS.fullname" . }}-stream-config
            items:
              - key: devicelogs.yaml
                path: devicelogs.yaml
        - name: status-ch
          configMap:
            name: {{ include "DIS.fullname" . }}-stream-config
            items:
              - key: devicestatus-clickhouse.yaml
                path: devicestatus-clickhouse.yaml      
        - name: dbc
          configMap:
            name: {{ include "DIS.fullname" . }}-stream-config
            items:
              - key: dbcdecoding.yaml
                path: dbcdecoding.yaml        
        - name: config
          configMap:
            name: {{ include "DIS.fullname" . }}-stream-config
            items:
              - key: config.yaml
                path: config.yaml
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
