apiVersion: v1
kind: Service
metadata:
  name: {{ include "dis.fullname" . }}
  labels:
    {{- include "dis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range $key, $value := .Values.service.ports }}
    - name: {{ $key }}
{{ toYaml $value | indent 6 }}
  {{- end }}
  selector:
    {{- include "dis.selectorLabels" . | nindent 4 }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "dis.fullname" . }}-attest
  labels:
    {{- include "dis.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
  selector:
    {{- include "dis.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
