input:
  broker:
    inputs:
      - label: "dimo_http_attestation_server"
        dimo_http_attestation_server:
            jwt: 
              token_exchange_issuer: ${TOKEN_EXCHANGE_ISSUER:https://auth.dev.dimo.zone/dex}
              token_exchange_key_set_url: ${TOKEN_EXCHANGE_KEY_SET_URL:https://auth.dev.dimo.zone/dex/keys}
            address: 0.0.0.0:9442 # TODO(ae): confirm
            path: /
            allowed_verbs:
              - POST
            timeout: 5s
            rate_limit: "connection_rate_limit"
            tls:
              enabled: true
              server_certs:
                - cert_file: /etc/ssl/certs/dis/tls.crt
                  key_file: /etc/ssl/certs/dis/tls.key
            sync_response:
              last_message_only: true
              status: ${!meta("response_status").or(200)}
              headers:
                Content-Type: application/octet-stream

      - label: "dimo_http_connection_server"
        dimo_http_connection_server:
            address: 0.0.0.0:9443
            path: /
            allowed_verbs:
              - POST
            timeout: 5s
            rate_limit: "connection_rate_limit"
            tls:
              enabled: true
              client_root_cas_file: /etc/ssl/certs/dis/root_ca.crt
              server_certs:
                - cert_file: /etc/ssl/certs/dis/tls.crt
                  key_file: /etc/ssl/certs/dis/tls.key
              require_mutual_tls: true
            sync_response:
              last_message_only: true
              status: ${!meta("response_status").or(200)}
              headers:
                Content-Type: application/octet-stream

pipeline:
  processors:
    - resource: "dimo_provider_input_count"

    # If label name change, update the alerts
    - label: "convert_cloudevent"
      dimo_cloudevent_convert:
        chain_id: ${DIMO_REGISTRY_CHAIN_ID:137}
        vehicle_nft_address: ${VEHICLE_NFT_ADDRESS:0xbA5738a18d83D41847dfFbDC6101d37C69c9B0cF}
        aftermarket_nft_address: ${AFTERMARKET_NFT_ADDRESS:0x9c94C395cBcBDe662235E0A9d3bB87Ad708561BA}
        synthetic_nft_address: ${SYNTHETIC_NFT_ADDRESS:0x4804e8D1661cd1a1e5dDdE1ff458A7f878c0aC6D}

    # If label name change, update the alerts
    - label: "convert_cloudevent_errors"
      catch:
        - log:
            level: WARN
            message: "failed to convert to cloudevent: ${!error()}"
            fields_mapping: |
                source = metadata("dimo_cloudevent_source")
                producer = this.producer.or("unknown")
                subject = this.subject.or("unknown")
                type = this.type.or("unknown")
                id = this.id.or("unknown")
        # mutate message for http response and metrics
        - mutation: |
              meta dimo_component = "dimo_cloudevent_convert"
              meta response_message = "failed to convert to cloudevent: " + error()
        # Update error count metric
        - resource: "dimo_error_count"
        # Send bad request response
        - resource: "dimo_bad_request_sync_response"
        # Drop the message
        - mapping: root = deleted()
    - label: "valid_cloudevent_switch"
      switch:
        - check: 'metadata("dimo_message_content").or("") == "dimo_partial_cloudevent"'
          processors:
            - resource: "dimo_partial_index_count"
        - check: 'metadata("dimo_message_content").or("") == "dimo_valid_cloudevent"'
          processors:
            - label: validate_fingerprint
              dimo_validate_fingerprint: {}
           # If label name change, update the alerts
            - label: convert_signals
              dimo_signal_convert:
                chain_id: ${DIMO_REGISTRY_CHAIN_ID:137}
                vehicle_nft_address: ${VEHICLE_NFT_ADDRESS:0xbA5738a18d83D41847dfFbDC6101d37C69c9B0cF}
    # If label name change, update the alerts
    - label: "processing_errors"
      catch:
      -  mutation: |
            meta response_message = if metadata("dimo_error_message").or("")  == error() { "failed to process cloudevent: " + error() } else { metadata("dimo_error_message").or("error") +": " + error()}
      - log:
          level: WARN
          message: "failed to process cloudevent"
          fields_mapping: |
            cloudevent_source = metadata("dimo_cloudevent_source").or("unknown")
            cloudevent_producer = metadata("dimo_cloudevent_producer").or("unknown")
            cloudevent_subject = metadata("dimo_cloudevent_subject").or("unknown")
            cloudevent_type = metadata("dimo_cloudevent_type").or("unknown")
            cloudevent_id = metadata("dimo_cloudevent_id").or("unknown")
            component = metadata("dimo_component").or("unknown")
            error_msg = metadata("dimo_error_message").or("unknown")
            error = if errored() { error() } else { metadata("error").or("unknown") }
      # Update error count metric
      - resource: "dimo_error_count"
      # Send bad request response
      - resource: "dimo_bad_request_sync_response"
      # Drop the message
      - mapping: root = deleted()

output:
  fallback:
    - label: "all_outputs"
      switch:
        retry_until_success: true
        strict_mode: true
        cases:
          # Output for valid signals
          - check: 'metadata("dimo_message_content").or("") == "dimo_valid_signal"'
            output:
              label: "send_signal"
              kafka:
                ack_replicas: false
                addresses:
                  - '${KAFKA_BOOTSTRAP_SERVERS:localhost}:${KAFKA_BOOTSTRAP_PORT:9092}'
                backoff:
                  initial_interval: 1s
                  max_elapsed_time: 30s
                  max_interval: 5s
                client_id: ${CONTAINER_NAME:localhost}-signal-output
                compression: '${KAFKA_COMPRESSION:none}'
                max_msg_bytes: 300000
                max_retries: 1
                max_in_flight: 20
                key: ${!metadata("dimo_cloudevent_subject")}
                partitioner: murmur2_hash
                batching:
                  count: 1000
                  byte_size: 200_000 # 0.5MB
                  period: 10ms
                target_version: 2.5.0
                timeout: 5s
                topic: '${KAFKA_SIGNALS_TOPIC:topic.device.signals}'
                metadata:
                  exclude_prefixes:
                    - dimo_cloudevent_index_value
                    - dimo_cloudevent_index
                    - dimo_cloudevent_producer
                    - dimo_cloudevent_source
                    - dimo_cloudevent_subject
                    - dimo_cloudevent_type
                    - dimo_cloudevent_id
                    - dimo_cloudevent_type
                    - dimo_message_content
                    - http_server_remote_ip
                    - http_server_request_path
                    - http_server_tls_cipher_suite
                    - http_server_tls_subject
          # Output for valid cloudevents
          - check: 'metadata("dimo_message_content").or("") == "dimo_valid_cloudevent" && metadata("dimo_cloudevent_index").or("") != ""'
            output:
              label: "send_valid_cloudevent"
              kafka:
                ack_replicas: false
                addresses:
                  - '${KAFKA_BOOTSTRAP_SERVERS:localhost}:${KAFKA_BOOTSTRAP_PORT:9092}'
                backoff:
                  initial_interval: 1s
                  max_elapsed_time: 30s
                  max_interval: 5s
                client_id: ${CONTAINER_NAME:localhost}-valid-output
                compression: '${KAFKA_COMPRESSION:none}'
                max_msg_bytes: 52428800
                max_retries: 2
                max_in_flight: 20
                key: ${!metadata("dimo_cloudevent_subject")}
                partitioner: murmur2_hash
                batching:
                  count: 0
                  byte_size: 1_000_000 # 1MB
                  period: 50ms
                target_version: 2.5.0
                timeout: 5s
                topic: '${KAFKA_VALID_CE_TOPIC:topic.device.validcloudevents}'

          # Output for partial cloudevents
          - check: 'metadata("dimo_message_content").or("") == "dimo_partial_cloudevent" && metadata("dimo_cloudevent_index").or("") != ""'
            output:
              label: "send_partial_cloudevent"
              kafka:
                ack_replicas: false
                addresses:
                  - '${KAFKA_BOOTSTRAP_SERVERS:localhost}:${KAFKA_BOOTSTRAP_PORT:9092}'
                backoff:
                  initial_interval: 1s
                  max_elapsed_time: 30s
                  max_interval: 5s
                client_id: ${CONTAINER_NAME:localhost}-partial-output
                compression: '${KAFKA_COMPRESSION:none}'
                max_msg_bytes: 52428800
                max_retries: 2
                max_in_flight: 20
                key: ${!metadata("dimo_cloudevent_source")}_${!metadata("dimo_cloudevent_id")}
                partitioner: murmur2_hash
                batching:
                  count: 0
                  byte_size: 1_000_000 # 1MB
                  period: 50ms
                target_version: 2.5.0
                timeout: 5s
                topic: '${KAFKA_PARTIAL_CE_TOPIC:topic.device.partialcloudevents}'
          - check: ''
            output:
              label: "drop_message"
              drop: {}
    - label: "error_output"
      drop: { }
      processors:
        - mutation: |
            meta response_message = "failed send message to kafka: " + error()
        - resource: "dimo_internal_error_sync_response"
