input:
  broker:
    inputs:
      - label: "dimo_http_attestation_server"
        dimo_http_attestation_server:
          jwt:
            token_exchange_issuer: ${TOKEN_EXCHANGE_ISSUER:https://auth.dev.dimo.zone/dex}
            token_exchange_key_set_url: ${TOKEN_EXCHANGE_KEY_SET_URL:https://auth.dev.dimo.zone/keys}
          address: ${DIS_ATTESTATION_ADDRESS:0.0.0.0:9442}
          path: /
          allowed_verbs:
            - POST
          timeout: 5s
          rate_limit: "connection_rate_limit"
          tls:
            enabled: false
          sync_response:
            last_message_only: true
            status: ${!meta("response_status").or(200)}
            headers:
              Content-Type: application/octet-stream

      - label: "dimo_http_connection_server"
        dimo_http_connection_server:
          address: ${DIS_CONNECTION_ADDRESS:0.0.0.0:9443}
          path: /
          allowed_verbs:
            - POST
          timeout: 5s
          rate_limit: "connection_rate_limit"
          tls:
            enabled: true
            client_root_cas_file: ${TLS_CA_CERT_FILE:/etc/ssl/certs/dis/root_ca.crt}
            server_certs:
              - cert_file: ${TLS_CERT_FILE:/etc/ssl/certs/dis/tls.crt}
                key_file: ${TLS_KEY_FILE:/etc/ssl/certs/dis/tls.key}
            require_mutual_tls: true
          sync_response:
            last_message_only: true
            status: ${!meta("response_status").or(200)}
            headers:
              Content-Type: application/octet-stream

pipeline:
  processors:
    - resource: "dimo_provider_input_count"

    # If label name change, update the alerts
    - label: "convert_cloudevent"
      dimo_cloudevent_convert:
        rpc_url: ${RPC_URL:https://polygon-rpc.com}
        chain_id: ${DIMO_REGISTRY_CHAIN_ID:137}
        vehicle_nft_address: ${VEHICLE_NFT_ADDRESS:0xbA5738a18d83D41847dfFbDC6101d37C69c9B0cF}
        aftermarket_nft_address: ${AFTERMARKET_NFT_ADDRESS:0x9c94C395cBcBDe662235E0A9d3bB87Ad708561BA}
        synthetic_nft_address: ${SYNTHETIC_NFT_ADDRESS:0x4804e8D1661cd1a1e5dDdE1ff458A7f878c0aC6D}

    # If label name change, update the alerts
    - label: "convert_cloudevent_errors"
      catch:
        - label: "log_cloudevent_convert_error"
          log:
            level: WARN
            message: "failed to convert to cloudevent: ${!error()}"
            fields_mapping: |
                source = metadata("dimo_cloudevent_source")
                producer = this.producer.or("unknown")
                subject = this.subject.or("unknown")
                type = this.type.or("unknown")
                id = this.id.or("unknown")
        # mutate message for http response and metrics
        - label: "set_cloudevent_convert_error_meta"
          mutation: |
              meta dimo_component = "dimo_cloudevent_convert"
              meta response_message = "failed to convert to cloudevent: " + error()
        # Update error count metric
        - resource: "dimo_error_count"
        # Send bad request response
        - resource: "dimo_bad_request_sync_response"
        # Drop the message
        - label: "delete_cloudevent_convert_error"
          mapping: root = deleted()
    - label: "valid_cloudevent_switch"
      switch:
        - check: 'metadata("dimo_message_content").or("") == "dimo_valid_cloudevent"'
          processors:
            - label: validate_fingerprint
              dimo_validate_fingerprint: {}
           # If label name change, update the alerts
            - label: convert_signals
              dimo_signal_convert:
                chain_id: ${DIMO_REGISTRY_CHAIN_ID:137}
                vehicle_nft_address: ${VEHICLE_NFT_ADDRESS:0xbA5738a18d83D41847dfFbDC6101d37C69c9B0cF}
            - label: convert_events
              dimo_event_convert: {}
    # If label name change, update the alerts
    - label: "processing_errors"
      catch:
      - label: "set_processing_error_meta"
        mutation: |
            meta response_message = if metadata("dimo_error_message").or("")  == error() { "failed to process cloudevent: " + error() } else { metadata("dimo_error_message").or("error") +": " + error()}
      - label: "log_processing_error"
        log:
          level: WARN
          message: "failed to process cloudevent"
          fields_mapping: |
            cloudevent_source = metadata("dimo_cloudevent_source").or("unknown")
            cloudevent_producer = metadata("dimo_cloudevent_producer").or("unknown")
            cloudevent_subject = metadata("dimo_cloudevent_subject").or("unknown")
            cloudevent_type = metadata("dimo_cloudevent_type").or("unknown")
            cloudevent_id = metadata("dimo_cloudevent_id").or("unknown")
            component = metadata("dimo_component").or("unknown")
            error_msg = metadata("dimo_error_message").or("unknown")
            error = if errored() { error() } else { metadata("error").or("unknown") }
      # Update error count metric
      - resource: "dimo_error_count"
      # Send bad request response
      - resource: "dimo_bad_request_sync_response"
      # Drop the message
      - label: "delete_processing_error"
        mapping: root = deleted()

output:
  switch:
    cases:
      - check: 'metadata("dimo_message_content").or("") == "dimo_valid_cloudevent"'
        output:
          label: "inproc_cloudevents"
          inproc: "dimo_cloudevents"
      - check: ''
        output:
          broker:
            pattern: fan_out
            outputs:
              - label: "inproc_clickhouse"
                inproc: "dimo_clickhouse"
              - label: "inproc_kafka"
                inproc: "dimo_kafka"
