input:
  inproc: "dimo_kafka"

output:
  switch:
    retry_until_success: true
    strict_mode: true
    cases:
      - check: 'metadata("dimo_message_content").or("") == "dimo_valid_signal"'
        output:
          label: "kafka_signals"
          kafka:
            ack_replicas: false
            addresses:
              - '${KAFKA_BOOTSTRAP_SERVERS:localhost}:${KAFKA_BOOTSTRAP_PORT:9092}'
            backoff:
              initial_interval: 1s
              max_elapsed_time: 30s
              max_interval: 5s
            client_id: ${CONTAINER_NAME:localhost}-signal-output
            compression: '${KAFKA_COMPRESSION:none}'
            max_msg_bytes: 300000
            max_retries: 1
            max_in_flight: 20
            key: ${!metadata("dimo_cloudevent_subject")}
            partitioner: murmur2_hash
            batching:
              count: 10000
              period: 1s
            target_version: 2.5.0
            timeout: 5s
            topic: '${KAFKA_SIGNALS_TOPIC:topic.device.signals}'
            metadata:
              exclude_prefixes:
                - dimo_cloudevent_index_value
                - dimo_cloudevent_index
                - dimo_cloudevent_producer
                - dimo_cloudevent_source
                - dimo_cloudevent_subject
                - dimo_cloudevent_type
                - dimo_cloudevent_id
                - dimo_message_content
                - http_server_remote_ip
                - http_server_request_path
                - http_server_tls_cipher_suite
                - http_server_tls_subject

      - check: 'metadata("dimo_message_content").or("") == "dimo_valid_event"'
        output:
          label: "kafka_events"
          kafka:
            ack_replicas: false
            addresses:
              - '${KAFKA_BOOTSTRAP_SERVERS:localhost}:${KAFKA_BOOTSTRAP_PORT:9092}'
            backoff:
              initial_interval: 1s
              max_elapsed_time: 30s
              max_interval: 5s
            client_id: ${CONTAINER_NAME:localhost}-event-output
            compression: '${KAFKA_COMPRESSION:none}'
            max_msg_bytes: 300000
            max_retries: 1
            max_in_flight: 20
            key: ${!metadata("dimo_cloudevent_subject")}
            partitioner: murmur2_hash
            batching:
              count: 10000
              period: 1s
            target_version: 2.5.0
            timeout: 5s
            topic: '${KAFKA_EVENTS_TOPIC:topic.device.events}'
            metadata:
              exclude_prefixes:
                - dimo_cloudevent_index_value
                - dimo_cloudevent_index
                - dimo_cloudevent_producer
                - dimo_cloudevent_source
                - dimo_cloudevent_subject
                - dimo_cloudevent_type
                - dimo_cloudevent_id
                - dimo_message_content
                - http_server_remote_ip
                - http_server_request_path
                - http_server_tls_cipher_suite
                - http_server_tls_subject

      - check: ''
        output:
          drop: {}
