replicaCount: 1
image:
  repository: dimozone/dis
  pullPolicy: IfNotPresent
  tag: 0064f91
  command:
    - /dis
  args:
    - '-w'
    - '-r'
    - /config/resources.yaml
    - '-c'
    - /config/config.yaml
    - streams
    - /streams/
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: true
  annotations: {}
  name: ''
podAnnotations: {}
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 10001
  runAsGroup: 10001
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - all
isDev: true
env:
  ENVIRONMENT: dev
  CLICKHOUSE_PORT: 9440
  CLICKHOUSE_SIGNAL_DATABASE: dimo
  CLICKHOUSE_INDEX_DATABASE: file_index
  KAFKA_SIGNALS_TOPIC: topic.device.signals
  KAFKA_VALID_CE_TOPIC: topic.device.validcloudevents
  KAFKA_PARTIAL_CE_TOPIC: topic.device.partialcloudevents
  DEVICES_APIGRPC_ADDR: devices-api-dev:8086
  KAFKA_BOOTSTRAP_SERVERS: kafka-dev-dimo-kafka-kafka-brokers
  LOG_LEVEL: INFO
  ALLOWABLE_TIME_SKEW: 5m
  DIMO_REGISTRY_CHAIN_ID: 80002
  VEHICLE_NFT_ADDRESS: '0x45fbCD3ef7361d156e8b16F5538AE36DEdf61Da8'
  AFTERMARKET_NFT_ADDRESS: '0x325b45949C833986bC98e98a49F3CA5C5c4643B5'
  SYNTHETIC_NFT_ADDRESS: '0x78513c8CB4D6B6079f813850376bc9c7fc8aE67f'
  TOKEN_EXCHANGE_KEY_SET_URL: https://auth.dev.dimo.zone/keys
  TOKEN_EXCHANGE_ISSUER: https://auth.dev.dimo.zone
service:
  type: ClusterIP
  ports:
    mon-http:
      port: 8888
      targetPort: mon-http
      protocol: TCP
    https:
      port: 443
      targetPort: https
      protocol: TCP
ports:
  - name: mon-http
    containerPort: 8888
    protocol: TCP
  - name: https
    containerPort: 9443
    protocol: TCP
  - name: http
    containerPort: 9442
    protocol: TCP
livenessProbe:
  httpGet:
    path: /ping
    port: mon-http
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1
readinessProbe:
  httpGet:
    path: /ready
    port: mon-http
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1
ingress:
  enabled: true
  className: nginx-direct
  annotations:
    nginx.ingress.kubernetes.io/limit-rps: '50'
  hosts:
    - host: dis.dev.dimo.zone
      paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              suffix: ''
              port:
                number: 443
  tls: []
certificate:
  commonName: dis.dev.dimo.zone
  issuer: cas-dev-dimo-ca-issuer
  caConfigMap: cae-dev-dimo-ca-certs
resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
podDisruptionBudget:
  maxUnavailable: 1
serviceMonitor:
  enabled: true
  path: /metrics
  port: mon-http
  interval: 30s
