rate_limit_resources:
  - label: "connection_rate_limit"
    local:
      count: 100000
      interval: 1s

processor_resources:
  - label: "dimo_error_count"
    metric:
      type: counter
      name: dimo_error_count
      labels:
        component: ${! metadata("dimo_component") }
        source: ${! metadata("dimo_cloudevent_source") }
        error: ${! metadata("error") }

  - label: "dimo_partial_index_count"
    metric:
      type: counter
      name: dimo_partial_index_count
      labels:
        source: ${! metadata("dimo_cloudevent_source").or("unknown") }

  - label: "dimo_bad_request_sync_response"
    processors:
      - mapping: |
          meta response_status = 400
          root = metadata("response_message").or("Bad Request")
      - sync_response: {}

  - label: "dimo_internal_error_sync_response"
    processors:
      - mapping: |
          meta response_status = 500
          root  =  metadata("response_message").or("Internal Error: Please try again later")
      - sync_response: {}
