name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted]
    strategy:
      matrix:
        go-version: ["1.23"]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: modVerify
        run: go mod verify

      - name: Run Tests
        run: go test -v ./...
