name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5

      - name: modVerify
        run: go mod verify

      - name: Run Tests
        run: go test -v ./...
